config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show, :index, :new] do
    resources :guides do
      resources :comments, :only => [:create, :delete, :destroy]
      member do
        post 'up_vote'
        post 'down_vote'
        post 'unvote'
      end
    end
  end

  authenticated :user do
    root to:  'users#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :guide
  belongs_to :user
  validates :body, length: { maximum: 200, minimum: 4, message: "Comment should be 4 to 200 letters long." }
  default_scope -> { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @guide = Guide.find(params[:guide_id])
    @comment = @guide.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
    respond_to do |format|
      format.html {
        flash[:notice] = "Commented!!"
        redirect_to :back
      }
      format.js
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to :back
  end

  private

    def comment_params
      params.require(:comment).permit(:body, :user)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <div id="comment">
    <%= link_to image_tag(comment.user.avatar(:small)), comment.user %>
    <small><%= link_to " #{comment.user.username }", comment.user %> <%= time_ago_in_words(comment.created_at) %> ago.
    <% if comment.user == current_user || current_user.admin? %>
      <%= link_to "Delete", user_guide_comment_path(comment.user, comment.guide, comment), method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
    </small>
    <br/>
    <span><%= comment.body %></span>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
  $(".comments").html("<%= escape_javascript(render @guide.comments) %>");
  $('#comment_body').val('');
  $("ul#notice").html('');
<% else %>
  $("ul#notice").html("")
  <% if @comment.errors.any? %>
    <% @comment.errors.messages.values.each do |msg| %>
      <% msg.each do |m| %>
        $("ul#notice").append($("<li />").html("<%= m.html_safe %>"))
      <% end %>
    <% end %>
  <% end %>
  $('#comment_body').val('');
<% end %>