config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show, :index, :new] do
    resources :guides do
      resources :comments, :only => [:create, :delete, :destroy]
      member do
        post 'up_vote'
        post 'down_vote'
        post 'unvote'
      end
    end
  end

  authenticated :user do
    root to:  'users#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :guides, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :username, presence: true, length: { minimum: 5 }
  has_attached_file :avatar, styles: { small: "70x70!", medium: "256x256!" }, default_url: "avatar_:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def admin?
    admin
  end

  def up_voted?(guide)
    vote = Vote.find_by(user_id: self.id, guide_id: guide.id)
    return false if vote.nil?
    return true if vote.has_attribute?(:up_vote) && vote.up_vote
  end

  def down_voted?(guide)
    vote = Vote.find_by(user_id: self.id, guide_id: guide.id)
    return false if vote.nil?
    return true if vote.has_attribute?(:up_vote) && vote.up_vote == false
  end

  def points
    sum = 0
    guides.each { |guide| sum += guide.votes }
    sum
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, only: [:show, :dashboard]
before_action :find_guides, only: [:show, :dashboard]
before_action :authenticate_user!, only: [:dashboard]
before_filter :verify_is_admin, only: [:index]

  def show
    @user = User.find(params[:id])
    @guides = @user.guides.all.order('created_at DESC').page(params[:page])
  end

  def dashboard

    if params[:search]
      unless / +/.match(params[:search]) || /%+/.match(params[:search]) || params[:search].length < 3
        @guides = Guide.where(['description LIKE :search OR title LIKE :search', search: "%#{params[:search]}%"]).order("created_at DESC").page(params[:page])
        if @guides.count == 0
          flash[:notice] = "No guides found."
          redirect_to :back
        end
      else
        flash[:notice] = "Phrase must be minimum 4 letter long."
        redirect_to :back
      end
    else
      @guides = Guide.all.order("created_at DESC").page(params[:page])
    end

  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to 'back'
  end

  private

    def find_user
      if params[:id].nil?
        @user = current_user
      else
        @user = User.find(params[:id])
      end
    end

    def find_guides
      @guides = Guide.where(user_id: @user).order("created_at DESC")
    end

    def verify_is_admin
      unless current_user.admin?
        redirect_to root_path
        flash[:danger] = "You need to be admin to proceed there."
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<%= render 'shared/header' %>
<div class="dashboard">
<div class="banner_dashboard">
</div>

  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>

  <div class="search">
  <%= form_tag root_path, method: 'get' do%>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  <% end %>
  </div>

  <div class="wrapper-skinny">
  <%= will_paginate @guides, :previous_label => '←', :next_label => '→' %>

  <div id="dashboard_episodes">
    <ul class="cf">
    <% @guides.each do |guide| %>
    <div class="guide_each">
      <%= link_to user_guide_path(guide.user_id, guide) do %>
        <li class="cf guide">
          <%= image_tag guide.thumbnail(:medium), class: "guide_thumbnail" %>
          <div id="text">
            <h3><%= guide.title %></h3>
            <span id="description"><%= truncate guide.description, length: 300 %></span>
            <br>
            <small><%= guide.created_at.strftime("%d %B %Y") %></small>
            <% if guide.votes >= 0 %>
              <span id="votes_dashboard"><i class="fa fa-arrow-up"></i><%= guide.votes %></span>
            <% else %>
              <span id="votes_dashboard"><i class="fa fa-arrow-down"></i><%= guide.votes %></span>
            <% end %>
          </div>
        </li>
      <% end %>
      <div class="authorized_links">
        <% if (guide.user_id == current_user.id) || current_user.admin? %>
          <%= link_to "Edit", edit_user_guide_path(guide.user_id, guide) %>
          <%= link_to "Delete", user_guide_path(guide.user_id, guide), method: :delete, data: { confim: "Are you sure?"} %>
        <% end %>
      </div>
    </div>
    <% end %>
    </ul>
  </div>

  <%= will_paginate @guides, class: "pagination bottom", :previous_label => '←', :next_label => '→' %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'shared/header' %>
<div id="user_index">
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user do %>
        <%= user.username %>
        <%= user.email %>
        <div class="authorized_links">
            <% if current_user.admin? && !user.admin?%>
              <%= link_to "Delete", user_path(user), method: :delete, data: { confim: "Are you sure?"} %>
            <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<div class="show_user">
  <div class="banner_show" >
  </div>

  <div class="wrapper-wide">
    <div class="user">
      <%= image_tag@user.avatar(:medium) %>
        <h3 class="name"><%= @user.username %></h3>
        <span class="user_description"><%= @user.description %></span>
        <span class="email">email: <%= @user.email %></span>
        <% if @user.points >= 0 %>
          <span class="points"><i class="fa fa-arrow-up"></i><%= @user.points %></span>
        <% else %>
          <span class="points"><i class="fa fa-arrow-down"></i><%= @user.points %></span>
        <% end %>
    </div>
  </div>

<div class="clear"></div>

  <div class="wrapper-skinny">

  <div id="dashboard_episodes user_episodes">
    <ul class="cf">
    <% @guides.each do |guide| %>
    <div class="guide_each">
      <%= link_to user_guide_path(guide.user_id, guide) do %>
        <li class="cf guide">
          <%= image_tag guide.thumbnail(:medium), class: "guide_thumbnail" %>
          <div id="text">
            <h3><%= guide.title %></h3>
            <span id="description"><%= truncate guide.description, length: 300 %></span>
            <br>
            <small><%= guide.created_at.strftime("%d %B %Y") %></small>
            <% if guide.votes >= 0 %>
              <span id="votes_dashboard"><i class="fa fa-arrow-up"></i><%= guide.votes %></span>
            <% else %>
              <span id="votes_dashboard"><i class="fa fa-arrow-down"></i><%= guide.votes %></span>
            <% end %>
          </div>
        </li>
      <% end %>
      <div class="authorized_links">
        <% if (guide.user_id == current_user.id) || current_user.admin? %>
          <%= link_to "Edit", edit_user_guide_path(guide.user_id, guide) %>
          <%= link_to "Delete", user_guide_path(guide.user_id, guide), method: :delete, data: { confim: "Are you sure?"} %>
        <% end %>
      </div>
    </div>
    <% end %>
    </ul>
  </div>

  <%= will_paginate @guides, class: "pagination bottom", :previous_label => '←', :next_label => '→' %>
  </div>
</div>