config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show, :index, :new] do
    resources :guides do
      resources :comments, :only => [:create, :delete, :destroy]
      member do
        post 'up_vote'
        post 'down_vote'
        post 'unvote'
      end
    end
  end

  authenticated :user do
    root to:  'users#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="cf header2">
    <h1 class="logo"><%= link_to "E-LEARN", root_path %></h1>
    <nav>
      <ul>
        <% unless user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Join us!", new_user_registration_path %></li>
        <% else %>
          <li>
            <%= link_to root_path do %>
              <i class="fa fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to new_user_guide_path(current_user) do%>
              <i class="fa fa-plus"></i> Add guide
            <% end %>
          </li>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i> Sign out
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-cog"></i> Settings
            <% end %>
          </li>
          <li>
            <%= link_to current_user do %>
              <i class="fa fa-user"></i> My account
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </header>