config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show, :index, :new] do
    resources :guides do
      resources :comments, :only => [:create, :delete, :destroy]
      member do
        post 'up_vote'
        post 'down_vote'
        post 'unvote'
      end
    end
  end

  authenticated :user do
    root to:  'users#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/guide.rb
class Guide < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes, dependent: :destroy
  self.per_page = 15
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 20 }
  validates :thumbnail, attachment_presence: true
  validates_attachment :thumbnail, content_Type: { content_type: ["image/jpeg", "image/png"] }
  has_attached_file :thumbnail, styles: { medium: "256x256", thumb: "300x300", small: "200x200>", hihi: "500x500" }
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/
  validate :thumbnail_size
  has_attached_file :video, styles: {
                                                    :medium => { :geometry => "640x480",:format => 'mp4' },
                                                    :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10} },
                                                    processors: [:ffmpeg]
validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
validates_attachment_presence :video, message: "- no video file selceted."

  def votes
    votes = self.up_votes - self.down_votes
  end

  private

    # Validates the size of an uploaded image.
    def thumbnail_size
      unless thumbnail.size.nil?
        if thumbnail.size > 5.megabytes
          errors.add(:picture, "should be less than 5MB")
        end
      end
    end
end

app/controllers/guides_controller.rb
require 'will_paginate/array'

class GuidesController < ApplicationController
before_filter :require_permition, except: [:show, :up_vote, :down_vote, :unvote]
before_action :find_user
before_action :find_guide, only: [:show, :edit, :destroy, :update]
before_action :authenticate_user!, except: [:show]

  def new
    @guide = @user.guides.new
  end

  def create
    @guide = @user.guides.new guide_params
    if @guide.save
      redirect_to user_guide_path(@user, @guide)
    else
      render 'new'
    end
  end

  def show
    @guides = Guide.where(user_id: @user).order("created_at DESC").reject{ |e| e.id == @guide.id}.paginate(:page => params[:page], per_page: 10)
  end

  def destroy
    @guide.delete
    redirect_to :back
  end

  def edit
  end

  def update
    if @guide.update guide_params
      redirect_to user_guide_path(@user, @guide), notice: "Episode successfully updated"
    else
      render 'edit'
    end
  end

  def up_vote
    @user = current_user
    @guide = Guide.find(params[:id])

    if vote = Vote.find_by(user_id: @user.id, guide_id: @guide.id)
      if (vote.up_vote == true)
        redirect_to :back
      else
        vote.up_vote = true
        vote.save
        @guide.down_votes -= 1
        @guide.up_votes += 1
        @guide.save
        respond_to do |format|
          format.html {
            flash[:notice] = "Vote changed!"
            redirect_to :back
          }
          format.js
        end
      end
    else
      Vote.create(user_id: @user.id, guide_id: @guide.id, up_vote: true)
      @guide.up_votes += 1
      @guide.save
      respond_to do |format|
        format.html {
          flash[:notice] = "Upvoted!"
          redirect_to :back
        }
        format.js
      end
    end
  end

    def down_vote
    @user = current_user
    @guide = Guide.find(params[:id])

    if vote = Vote.find_by(user_id: @user.id, guide_id: @guide.id)
      unless vote.up_vote
        redirect_to :back
      else
        vote.up_vote = false
        vote.save
        @guide.down_votes += 1
        @guide.up_votes -= 1
        @guide.save
        respond_to do |format|
          format.html {
            flash[:notice] = "Vote changed!"
            redirect_to :back
          }
          format.js
        end
      end
    else
      Vote.create(user_id: @user.id, guide_id: @guide.id, up_vote: false)
      @guide.down_votes += 1
      @guide.save
      respond_to do |format|
        format.html {
          flash[:notice] = "Vote changed!"
          redirect_to :back
        }
        format.js
      end
    end
  end

  def unvote

    @user = current_user
    @guide = Guide.find(params[:id])

    vote = Vote.find_by(user_id: @user.id, guide_id: @guide.id)

    if vote.up_vote
      @guide.up_votes -= 1
      respond_to do |format|
        format.html {
          flash[:notice] = "Upvote cancelled!"
          redirect_to :back
        }
        format.js
      end
    else
      @guide.down_votes -= 1
      respond_to do |format|
        format.html {
          flash[:notice] = "Downvote cancelled!"
          redirect_to :back
        }
        format.js
      end
    end

    @guide.save
    vote.destroy

  end

  private

    def guide_params
      params.require(:guide).permit(:title, :description, :thumbnail, :video)
    end

    def find_user
      @user = User.find(params[:user_id])
    end

    def find_guide
      @guide = Guide.find(params[:id])
    end

    def require_permition
      @user = User.find(params[:user_id])
      if ((current_user != @user) && !current_user.admin?)
        redirect_to root_path, notice: "Sorry, you're not allowed to view this page"
      end
    end

end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_down_vote.html.erb
<%= link_to down_vote_user_guide_path(user_id: user, guide_id: guide), method: :post, class: "downvote_active", remote: true do %>
<li><i class="fa fa-arrow-down fa-lg cf"></i></li>
<% end %>

app/views/guides/_unvote.html.erb
<%= link_to unvote_user_guide_path(user_id: user, guide_id: guide), method: :post, class: "inactive", remote: true do %>
<li><i class="fa fa-undo fa-lg cf"></i></li>
<% end %>

app/views/guides/_up_vote.html.erb
<%= link_to up_vote_user_guide_path(user_id: user, guide_id: guide), method: :post, class: "upvote", remote: true do %>
<li><i class="fa fa-arrow-up fa-lg active cf"></i></li>
<% end %>

app/views/guides/down_vote.js.erb
$("#up_<%= @guide.id %>").html("<%= escape_javascript(render 'guides/up_vote', guide: @guide, user: @user) %>");
$("#down_<%= @guide.id %>").html("<%= escape_javascript(render 'guides/unvote', guide: @guide, user: @user) %>");

$(".rate").html("<%= @guide.votes %>")

app/views/guides/edit.html.erb
<%= render 'shared/header' %>
<div class="edit_tutorial">
  <div class="banner_show">
  </div>

  <div class="wrapper-skinny" id="sign_up new_guide">
  <h2>Edit guide</h2>

  <%= form_for ([@user, @guide]) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="field file_upload">
      <%= f.label :thumbnail %>
      <%= f.file_field :thumbnail %>
    </div>

    <div class="field file_upload">
      <%= f.label :video %>
      <%= f.file_field :video %>
    </div>

    <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/guides/new.html.erb
<%= render 'shared/header' %>
<div class="new_guide">
  <div class="banner_show" >
  </div>

  <div class="wrapper-skinny" id="sign_up new_guide">
  <h1>Create guide!</h1>

  <%= form_for ([@user, @guide]), html: { multipart: true } do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="field file_upload">
      <%= f.label :thumbnail %>
      <%= f.file_field :thumbnail %>
    </div>

    <div class="field file_upload">
      <%= f.label :video %>
      <%= f.file_field :video %>
    </div>

    <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/guides/show.html.erb
<%= render 'shared/header' %>
<div class="show_guide">

  <div class="links">
    <div class="wrapper-skinny">
        <li><%= link_to "Dashboard", root_path %></li>
        <span> / </span>
        <li class="current"><%= @guide.title %></li>
    </div>
  </div>

  <div class="guide_content">
    <div class="wrapper-guide">
      <% if @guide.video? %>
      <div class="ratings" >
      <ul id="voteguide">
        <% unless current_user.up_voted?(@guide) %>
          <span id="up_<%= @guide.id %>"><%= render 'guides/up_vote', guide: @guide, user: @user %></span>
        <% else %>
          <span id="up_<%= @guide.id %>"><%= render 'guides/unvote', guide: @guide, user: @user %></span>
        <% end %>
        <% unless current_user.down_voted?(@guide) %>
          <span id="down_<%= @guide.id %>"><%= render 'guides/down_vote', guide: @guide, user: @user %></span>
        <% else %>
          <span id="down_<%= @guide.id %>"><%= render 'guides/unvote', guide: @guide, user: @user %></span>
        <% end %>
        <% if @guide.votes >= 0 %>
          <li><span class="rate positive"> <%= @guide.votes %></span></li>
        <% else %>
          <li><span class="rate negative"> <%= @guide.votes %></span></li>
        <% end %>
        </ul>
      </div>
      <div class="guide_video">
        <%= video_tag @guide.video.url(:medium), controls: true, style: "max-width: 100%;"%>
      </div>
      <% end %>

    </div>

      <div class="description">
            <h3><%= @guide.title %><small class="time"><%= @guide.created_at.strftime("%d %B %Y") %></small></h3>
        <span><%= @guide.description %></span>
      </div>
  </div>

  <div id="episodes">
    <h4>More <%= @user.username %>'s videos:</h4>
        <ul class="cf">
          <% @guides.each do |guide| %>
            <li class="cf guide">
              <%= link_to user_guide_path(guide.user_id, guide) do %>
                <%= image_tag guide.thumbnail(:medium), class: "guide_thumbnail" %>
                <div id="text">
                  <h3><%= guide.title %> </h3>
                  <span id="description"><%= truncate guide.description, length: 300 %></span>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
        <%= will_paginate @guides, :previous_label => '←', :next_label => '→' %>
  </div>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<ul id="notice"></ul>

  <div class="add_comment">
    <%= form_for [@user, @guide, Comment.new], remote: true  do |f| %>
      <p>
        <%= f.text_area :body %>
      </p>
      <p><%= f.submit "Add comment" %></p>
    <% end %>
  </div>
  <div class="comments">
    <%= render @guide.comments %>
  </div>
</div>

app/views/guides/unvote.js.erb
<% if Vote.find_by(user_id: @user.id, guide_id: @guide.id, up_vote: true) %>
  $("#up_<%= @guide.id %>").html("<%= escape_javascript(render 'guides/up_vote', guide: @guide, user: @user) %>");
<% else %>
  $("#down_<%= @guide.id %>").html("<%= escape_javascript(render 'guides/down_vote', guide: @guide, user: @user) %>");
<% end %>
$(".rate").html("<%= @guide.votes %>")

app/views/guides/up_vote.js.erb
$("#down_<%= @guide.id %>").html("<%= escape_javascript(render 'guides/down_vote', guide: @guide, user: @user) %>");
$("#up_<%= @guide.id %>").html("<%= escape_javascript(render 'guides/unvote', guide: @guide, user: @user) %>");

$(".rate").html("<%= @guide.votes %>")